### ISSUE TITLE
Coding & UX Research With AI

### ISSUE THREAD

**Issue by RobotsBuildingEducation** [RobotsBuildingEducation/RobotsBuildingEducation#13]
One of the next major software goals from Robots Building Education is to make the code more serviceable for other people.

This means that the code should be extremely easy to work with if someone decides to fork it and take it in their own direction.
From a business POV, this also makes it easier to service and support non-technical people more effeciently.

The app is fairly small, but mostly written to generate revenue with plenty of after-midnight decisions. 

For now, I'm curious to see how AI can help individuals refactor and improve code. So rather than focusing on execution and implementation, we're going to focus on gaining and reporting knowledge:

- What prompts are useful for refactoring code?
- Are there creative prompts beginners can come up with that more senior engineers don't?
- Are there knowledge barriers where more senior engineers can discover useful prompts that beginners aren't aware of?
- How effective is AI at large design and refactoring choices?
- How stable are these refactors?

The list can go on with a number of insights, those listed above are just immediate things that come to mind with no real priority.
**A good rule of thumb that you've found good or meaningful insight is if it excites you to report it to someone or somewhere.**

**Comment by RobotsBuildingEducation** [comment]
@MiffyBruna @nfa1 

Some pretty promising results "refactoring with code" tonight. I've had this in mind for some time.

Basically, I wrote a bunch of code late and night without considering too many consequences of doing it that way. I threw it into ChatGPT for some cleaning after configuring a few lines and it would return a nice sheet of data back. It was fairly stable.

Lesson learned, chatGPT lets you take risks when it comes to building stuff. It saves time & energy in a lot of interesting ways

- [`<PromptCombiner9000 />` 🍝Before](https://github.com/RobotsBuildingEducation/RobotsBuildingEducation/pull/30/files#diff-27d0de8690a39bb2ab636363e74ecfb9db66b37ece31450c61864f19258e24d4)
- [`<PromptCombiner9000 />` After ✨](https://github.com/RobotsBuildingEducation/RobotsBuildingEducation/pull/30/files#diff-d80fd45aef51f46e4d24ee40be4ce04b23114c11847608650d2a098ada1d0e5f)

- [`<Prompts />` 🍝Before & After ✨](https://github.com/RobotsBuildingEducation/RobotsBuildingEducation/pull/30/files#diff-4b1e266fb9b40df81b5c07a15285554842283efd04287fb1436587536a897d21)

**Comment by RobotsBuildingEducation** [comment]
I'll have you folks review/merge the code to `main` so you guys have more fingerprints on this codebase. I usually just smash merge but I should probably stop doing that sooner than later lol

**Comment by nfa1** [comment]
Great to hear about your late-night coding session! ChatGPT has been a real lifesaver for me too when it comes to debugging and refactoring my code.

Excited to help out with any code review/merge so feel free to send some my way. 🫡
